FROM ubuntu:20.04

LABEL mainteiner = "Amairani DI"
LABEL version = "v0.1"
LABEL description = "Imagen para desarrollar con python"


RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip3 install web.py
RUN pip3 install requests
RUN pip3 install simplejson